apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    id: C0911182       
    app: nginx
    env: dev
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      id: C0911182
  template:
    metadata:
      labels:
        id: C0911182   
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
          ports:
            - containerPort: {{ .Values.service.port }}