apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    id: C0911182       # replace with your actual college ID
    app: nginx
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: C0911182
  template:
    metadata:
      labels:
        id: C0911182   # replace with your actual college ID
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: vakulaannapareddy/ica3  # replace with your Docker image name
          ports:
            - containerPort: 8080